version: "3"
services:
    web:
        environment:
            - DB_CONNECTION_STRING=Server=db,1433;Database=Fleet;User=sa;Password=thisIS300spartans
        build: .
        ports:
            - "8080:80"
        depends_on:
            - db
            - data
        networks:
            - consumer-producer
    data:
        environment:
            - DB_CONNECTION_STRING=Server=db,1433;Database=Fleet;User=sa;Password=thisIS300spartans
        build:
            context: ./DockerMigrations/AppData
        depends_on:
            - db
        networks:
            - consumer-producer
    db:
        image: "mcr.microsoft.com/mssql/server:2019-CU1-ubuntu-16.04"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "thisIS300spartans"
            ACCEPT_EULA: "Y"
        networks:
            - consumer-producer
networks:
    consumer-producer:
